[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "super-prompt-core"
version = "0.0.1"
description = "Core engine for Super Prompt (state machine, AMR, context, SDD)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "Super Prompt"}]

